name: Tests

on:
  pull_request:

  push:
    branches:
      - main
      - 'feature/**'
      - 'support/**'

  workflow_dispatch:
    inputs:
      runner:
        description: Run tests on
        type: choice
        default: ubuntu-latest
        options:
          - macos-latest
          - ubuntu-latest
          - windows-latest

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install:
    name: Install
    runs-on: ${{ github.event.inputs.runner || 'ubuntu-latest' }}

    env:
      PUPPETEER_SKIP_DOWNLOAD: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/workflows/actions/install-node

  build:
    name: Build
    runs-on: ${{ github.event.inputs.runner || 'ubuntu-latest' }}
    needs: [install]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore dependencies
        uses: ./.github/workflows/actions/install-node

      - name: Build
        uses: ./.github/workflows/actions/build

      - name: Type declarations
        run: npm run build:types

  lint:
    name: ${{ matrix.task.description }}
    runs-on: ${{ github.event.inputs.runner || 'ubuntu-latest' }}
    needs: [install]

    strategy:
      fail-fast: false

      matrix:
        task:
          - description: Lint Sass
            name: lint-scss
            run: npm run lint:scss
            cache: .cache/stylelint

          - description: Lint JavaScript
            name: lint-js
            run: npm run lint:js
            cache: .cache/eslint

          - description: EditorConfig
            name: lint-editorconfig
            run: npm run lint:editorconfig

          - description: Prettier
            name: lint-prettier
            run: npm run lint:prettier
            cache: .cache/prettier

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore dependencies
        uses: ./.github/workflows/actions/install-node

      - name: Cache linter
        if: ${{ matrix.task.cache }}
        uses: actions/cache@v3
        with:
          key: ${{ matrix.task.name }}-cache-${{ runner.os }}
          path: ${{ matrix.task.cache }}

      - name: Run lint task
        run: ${{ matrix.task.run }}

  test:
    name: ${{ matrix.task.description }}
    runs-on: ${{ github.event.inputs.runner || 'ubuntu-latest' }}
    needs: [install]

    strategy:
      fail-fast: false

      matrix:
        task:
          - description: Nunjucks macro tests
            name: test-macro
            run: npx jest --color --selectProjects "Nunjucks macro tests"
            cache: .cache/jest

          - description: JavaScript unit tests
            name: test-unit
            run: npx jest --color --maxWorkers=2 --selectProjects "JavaScript unit tests" --coverage --testLocationInResults
            cache: .cache/jest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore dependencies
        uses: ./.github/workflows/actions/install-node

      - name: Cache task
        if: ${{ matrix.task.cache }}
        uses: actions/cache@v3
        with:
          key: ${{ matrix.task.name }}-cache-${{ runner.os }}
          path: ${{ matrix.task.cache }}

      - name: Run test task
        run: ${{ matrix.task.run }}

      - name: Save test coverage
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.task.description }} coverage
          path: coverage
          if-no-files-found: ignore

  verify:
    name: ${{ matrix.task.description }}
    runs-on: ${{ github.event.inputs.runner || 'ubuntu-latest' }}
    needs: [install, build]

    strategy:
      fail-fast: false

      matrix:
        task:
          - description: Verify package build
            name: test-build-package
            run: npm run build:package

          - description: Verify distribution build
            name: test-build-release
            run: npm run build:release

          - description: JavaScript behaviour tests
            name: test-behaviour
            run: npx jest --color --maxWorkers=2 --selectProjects "JavaScript behaviour tests"
            cache: .cache/jest

          - description: JavaScript component tests
            name: test-component
            run: npx jest --color --maxWorkers=2 --selectProjects "JavaScript component tests"
            cache: |
              .cache/jest
              .cache/puppeteer

          - description: Accessibility tests
            name: test-accessibility
            run: npx jest --color --maxWorkers=2 --selectProjects "Accessibility tests"
            cache: |
              .cache/jest
              .cache/puppeteer

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore dependencies
        uses: ./.github/workflows/actions/install-node

      - name: Restore build
        uses: ./.github/workflows/actions/build

      - name: Cache task
        if: ${{ matrix.task.cache }}
        uses: actions/cache@v3
        with:
          key: ${{ matrix.task.name }}-cache-${{ runner.os }}
          path: ${{ matrix.task.cache }}

      - name: Run verify task
        run: ${{ matrix.task.run }}

  regression:
    name: Percy
    needs: [install, build]

    # Run existing "Percy screenshots" workflow
    # (after install and build have been cached)
    uses: ./.github/workflows/screenshots.yml
    secrets: inherit
